# Site settings
author: Anika Christopher
title: 
header-img: img/home-bg.png
email: anika.mchristopher@gmail.com
copyright_name: Anika Christopher
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: AnikaChristoph4
github_username:  anikachristopher

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
